runtime: php55
api_version: 1

handlers:
- url: /lib/(.*)
  script: lib/\1
  
- url: /data/(.*)$
  script: data/\1

- url: /main.php
  script: main.php
  
- url: /index.php
  script: index.php
  
- url: /genocide.php
  script: genocide.php
  
- url: /genocide2.php
  script: genocide2.php
  